changes to tools

diff --git a/tools/apktool b/tools/apktool
--- a/tools/apktool
+++ b/tools/apktool
@@ -42,7 +42,7 @@ prog="${progdir}"/`basename "${prog}"`
 cd "${oldwd}"
 
 
-jarfile=baksmali-1.2.3.jar
+jarfile=apktool-1.3.1.jar
 libdir="$progdir"
 if [ ! -r "$libdir/$jarfile" ]
 then
@@ -69,9 +69,27 @@ while expr "x$1" : 'x-J' >/dev/null; do
 done
 
 if [ "$OSTYPE" = "cygwin" ] ; then
-	jarpath=`cygpath -w  "$libdir/$jarfile"`
+    jarpath=`cygpath -w  "$libdir/$jarfile"`
 else
-	jarpath="$libdir/$jarfile"
+    jarpath="$libdir/$jarfile"
 fi
 
-exec java $javaOpts -jar "$jarpath" "$@"
+# set the default java
+javabin=$(which java)
+
+# attempt to find SOME 1.6 java binary
+for i in $(find /opt -name 'java' 2>/dev/null | grep "1.6") ; do
+    if [ -x "${i}" ] ; then
+        # we have an executable that MAY be 1.6, so set and break
+        javabin="${i}"
+        break
+    fi
+done
+
+# now just verify we have something to execute
+if [ ! -x "${javabin}" ] ; then
+    echo `basename "$prog"`": can't find java executable [${javabin}]"
+    exit 1
+fi
+
+exec "$javabin" $javaOpts -jar "$jarpath" "$@"
